production:
    - 'Main \((Production|Stable)\)'

staging:
    - 'Development \((Staging|Unstable)\)'

rarely repeatable:
    - '### ?Repeatability\n+Rarely'

sometimes repeatable:
    - '### ?Repeatability\n+Sometimes'

always repeatable:
    - '### ?Repeatability\n+Always'

unknown repeatability:
    - '### ?Repeatability\n+Can''t tell'
