production:
    - 'Main \((Production|Stable)\)'

staging:
    - 'Development \((Staging|Unstable)\)'

rarely repeatable:
    - 'Repeatability\nRarely'

sometimes repeatable:
    - 'Repeatability\nSometimes'

always repeatable:
    - 'Repeatability\nAlways'

unknown repeatability:
    - 'Repeatability\nCan\'t tell'
