production:
    - 'Main \((Production|Stable)\)'

staging:
    - 'Development \((Staging|Unstable)\)'

rarely repeatable:
    - 'Rarely'

sometimes repeatable:
    - 'Sometimes'

always repeatable:
    - 'Always'

unknown repeatability:
    - 'Can\'t tell'
