name: Bug report or issue
description: Something isn't working as intended.
labels: bug, unreviewed
assignees: Hexcede
body:
  - type: markdown
    id: info
    attributes:
      value: |
        If you lost progress or have a more sensitive issue you should create a ticket in our Discord server!

        ## What makes a good bug report?
        - Explain how to reproduce the bug as best you can
        - Be as specific and detailed as possible
        - Provide screenshots, videos, or explanations of what happens if possible
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting your report, make sure you do the checklist
      options:
        - label: Do a quick check for similar/duplicate reports to reply under instead
          required: true
        - label: Give a detailed description of what's wrong
          required: true
        - label: Provide detailed reproduction steps for the bug (if applicable)
          required: true
  - type: markdown
    id: info
    attributes:
      value: |
        ---
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? What did you expect to happen?
      description: Be as detailed as possible
      placeholder: Tell us what you see!
      value: "My ship seemingly gets randomly duplicated or deleted when I warp sometimes. I can't seem to make it happen consistently, I have only encountered it a few times by warping.\n\nI can't get `Filter` to work with `Kiln`. It can't find `Sand` through a `Filter` even when it has been specifically configured for `Sand`. I expect the `Kiln` to be able to find `Sand` through the filter but for some reason it doesn't."
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can we try to trigger the bug again?
      description: This is important so that we can reproduce the bug in a debug environment
      placeholder: Reproduction steps
      value: " 1. Warp to space.\n 2. Warp back to the planet.\n 3. Warp to space again and repeat until something happens.\n 4. Sometimes, your ship will disappear or be duplicated.\n\n 1. Set up a `Filter` for `Sand` that's attached to a `Kiln` and a `Sand` bin.\n 2. Turn on the `Kiln` and observe that it can't find the `Sand`."
  - type: dropdown
    id: frequency
    attributes:
      label: Repeatability
      description: How repeatable is the bug? Can you make it always happen, or, does it only happen sometimes?
      multiple: false
      options:
        - Always
        - Sometimes
        - Rarely
        - Can't tell
      default: 0
    validations:
      required: true
  - type: textarea
    id: model-code
    attributes:
      label: Do you have a model that reproduces the bug?
      description: Paste model code below if applicable
      placeholder: Reproduction model
      render: json
