name: Feature or suggestion
description: I want to suggest a feature or change.
labels: unreviewed
assignees: Hexcede
type: Feature
body:
  - type: markdown
    id: info
    attributes:
      value: |
        - Focus on problems you want to resolve, rather than particular solutions you have in mind
        - Try to describe what you think needs to be improved, how, why, etc
        - Avoid going into specific stats when you don't have to
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: |
        Before submitting your suggestion, make sure you do the checklist
      options:
        - label: Do a quick check for similar/duplicate suggestions to reply under instead
          required: true
        - label: Make sure your suggestion primarily focuses on making improvements
          required: true
        - label: Have a good explanation for how the problem you're trying to solve is important
          required: true
  - type: markdown
    id: info
    attributes:
      value: |
        ---
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What does your suggestion focus on?
      multiple: false
      options:
        - A game mechanic (e.g. a part, a feature, etc)
        - A design problem (e.g. clunky UX, a balancing issue, etc)
        - A documentation issue (e.g. incorrect description, missing information, etc)
        - A programming feature (e.g. APIs, tweaks, changes, etc)
      default: 0
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem are you focusing on, or what are you looking to improve?
      description: Describe the problem. It can be simple, broad, or vague, but be as specific as possible
      placeholder: What are you looking to improve?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: What do you have in mind, if anything?
      description: Describe how you think the problem should be solved. Don't worry about specific details, stats, etc
      placeholder: Suggest something new and shiny
  - type: textarea
    id: justification
    attributes:
      label: Why is your proposal a good idea, if you had one?
      description: How will your proposal solve the problem you posed or make an improvement?
      placeholder: My feature or change is a good idea because it...
