name: Feature or suggestion
description: I want to suggest a feature or change.
labels: enhancement, unreviewed
assignees: Hexcede
body:
  - type: markdown
    id: info
    attributes:
      value: |
        - Focus on problems rather than the solution you have in mind
        - Describe what improvements you think should be made
        - Avoid going into specific stats when you don't have to
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: |
        Before submitting your suggestion, make sure you do the checklist
      options:
        - label: Do a quick check for similar/duplicate suggestions to reply under instead
          required: true
        - label: Make sure your suggestion focuses on a problem, even if its broad
          required: true
        - label: Have a good explanation for how the problem you're trying to solve is important
          required: true
  - type: markdown
    id: info
    attributes:
      value: |
        ---
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What does your suggestion focus on?
      multiple: false
      options:
        - A game mechanic (e.g. a part, a feature, etc)
        - A design problem (e.g. clunky UX, a balancing issue, etc)
        - A documentation issue (e.g. incorrect description, missing information, etc)
        - A programming feature (e.g. APIs, tweaks, changes, etc)
      default: 0
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Why are you making your suggestion?
      description: What do you think makes your feature or change a good idea? What will it do for the game?
      placeholder: My feature or change is a good idea because it...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: What do you propose? What should change, or what should be added?
      description: Don't worry about specific details, stats, etc, those are for us to figure out
      placeholder: Suggest something new and shiny
    validations:
      required: true
